# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20161103_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='draw',
        ),
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.ManyToManyField(blank=True, related_name='draw', to='team.Team'),
        ),
    ]
