# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('WN', '勝利'), ('LS', '敗北'), ('DR', '引き分け'), ('YT', '未実施')], default='YT', max_length=2),
        ),
    ]
