# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '選択肢', 'verbose_name_plural': '選択肢の複数形'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text', '-pub_date'], 'verbose_name': '質問', 'verbose_name_plural': '質問の複数形'},
        ),
    ]
